### ISSUE TITLE
Coin Error

### ISSUE THREAD

**Issue by luke86** [psomashekar/pr4m0d-MISTer-bin#16]
In 2 player mode when pushing the coin button sometimes the game crashes and only shows the message "Coin Error" on the screen. It happened once at the time beginning of Batrider and once when only 1 player pushed the button during late game in Battle Garegga. 

It's reproduce ablehnen by starting the core until the title screen shows up and then mashing the coin button on 2 controllers until the error occurs. 

Workaround: free play mode via dip switch exists 

Testen with the following Games:
Batrider
Battle Garegga
Battle Bakraid

**Comment by suverman** [comment]
Coin error occurs on MAME and the PCB as well. You cannot keep the coin button pressed for a long time. It needs to be momentary.

**Comment by luke86** [comment]
Alright thanks that's good to know. Good that we can activate free play mode then!

**Comment by psomashekar** [comment]
@luke86 this is normal functionality, just tested on the real board. It happens when you hold the coin button down for too long. Guwange and other games also have a similar functionality. I use it to reset the game if I die unintentionally and want to start over.
