### ISSUE TITLE
No Pause Button 

### ISSUE THREAD

**Issue by luke86** [psomashekar/pr4m0d-MISTer-bin#17]
The Core has no Pause Button like other arcade cores normally have, would be a great feature. Thanks for the hard work!

**Comment by suverman** [comment]
Also rewind feature would be nice and if possible fast forward...

**Comment by psomashekar** [comment]
This is a good idea, but have to research how it might work as there are multiple processes and cpus involved.

**Comment by atrac17** [comment]
> This is a good idea, but have to research how it might work as there are multiple processes and cpus involved.

It's implemented and in the PR I'm working on. Don't spend time on it.

**Comment by atrac17** [comment]
Pushed with those PRs mister devel
