### ISSUE TITLE
Battle Garegga - core stops working after final boss

### ISSUE THREAD

**Issue by luke86** [psomashekar/pr4m0d-MISTer-bin#22]
I finished Battle Garegga 2 times with 2 different ships now and after the final boss (don't know if there is a true final boss because I'm not good enough) the game writes Congratulations on the screen and goes black.

The screen just stays black and there is no music or any reaction to button presses. I still can open the Mister Menu and restart the core.

**Comment by psomashekar** [comment]
I'll take a look at this. That is strange indeed.

**Comment by psomashekar** [comment]
@luke86 when you encountered this, after the black screen, was there music playing at all? or does it just freeze and stop?

**Comment by zakk4223** [comment]
Can confirm I also see this happening. No music, just a black screen/freeze.

**Comment by luke86** [comment]
I made a Video of it happening here, hope it helps:
https://photos.app.goo.gl/i8Bw9uMsUoNDZF6A7

For me it happened every time so far, I made 3 Runs using 2 different Ship types. I can rule out that it has something to do with me using one of the unlockable characters because it also happended with the second standard ship.

**Comment by psomashekar** [comment]
hmm, so kidpanda says if you put in coins on that black screen, sounds do play, so I wonder if this is some weird phenomenon with a rom or dipswitch setting of some kind gone bad? It just seems weird the whole game plays through except that part. I don't think there's anything special on that screen at all, and if sounds are playing, the core isn't frozen.

**Comment by zakk4223** [comment]
It occurs right at a transition (the screen goes fades to black and the credit scroll starts) so you wouldn't normally hear music or anything there. 

I just realized my custom garegga code has a problem that looks almost exactly like this (black screen on transition, coin sounds etc). Can't say if it is related or not, but at least it happens at game start so it might be easier to narrow down.
Here is the modification: https://github.com/zakk4223/battle-garegga-patches (look in the mister directory for an MRA). The actual code is in patch.s

Enable the 'stage edit' dip switch. When you start a credit you should see some extra text on the screen (rank readouts, autofire rate etc). When that credit ends, go back to the title screen and try to start another credit. Black screen, credit sound will still work etc. If you disable the stage edit dip it will 'unstick' and work normally. (But that dip causes it to skip a bunch of code).
The offending label in the patch.s is 'custom_values_display'. 

I've tried completely removing any copies to text ram with no change in behavior. The only way I can make it not black screen is if I comment out a bunch of the code (with no pattern as to any one particular piece being the offending code). It's almost like it is related to the number of instructions being executed. The patch runs flawlessly on real hardware. I'll keep digging around to see if I can narrow it down to anything and if that might also be relevant to the end-game issue.

**Comment by psomashekar** [comment]
It sounds related. Now what about other versions of the ROM? Do they exhibit the same behavior? I think with a small change I can make the bootleg version work (I think the extra text layer is done differently).

Can this be reproduced in an emulator? I can take a look at the address bus sequence for when the issue happens, so that might key us into what is happening exactly.

**Comment by psomashekar** [comment]
kidpanda mentioned this too I think, but I notice when the stage edit is on, the transitions are longer between screens than if it is off. So mabe there is some weirdness happening with this.

**Comment by zakk4223** [comment]
The issue with my code cannot be reproduced in an emulator; it was primarily developed under mame and then made to work on real hardware. I've also never seen the black screen at the end of game on any emulator.

I will see if other versions do it; I can't use my modifications as they would probably require re-finding all the program rom offsets and I'm not setup for that right now. I can check end game easily enough.

I also just discovered something: if I modify my code to replace the entire 'custom_values_routine' with approximately 120 "add.w #$1, d1" instructions, the game will freeze in the same way on the game start transition.

**Comment by psomashekar** [comment]
@zakk4223 @luke86 please try latest rbf, I fixed this issue.

**Comment by zakk4223** [comment]
Ending no longer black screens now! The transitions still seem slower when stage edit dip is on with my code, but it no longer freezes at least.

What was the issue?

**Comment by psomashekar** [comment]
https://github.com/MiSTer-devel/Arcade-MiSTer_Raizing/pull/3
