### ISSUE TITLE
Bakraid extend DIP switch settings mislabeled

### ISSUE THREAD

**Issue by Steven-Pendleton** [psomashekar/pr4m0d-MISTer-bin#24]
Bakraid extend DIPs are labelled incorrectly in the DIP switch menu. Looks like you have them using the Batrider values. Bakraid extend settings should be 200000 each (default), 300000 each, and 400000 each.

**Comment by atrac17** [comment]
Fixed in the PR I am working on, don't waste time on it @psomashekar.
