### ISSUE TITLE
Battle Garegga no sound when coin 1 set to free play 

### ISSUE THREAD

**Issue by hardyhell** [psomashekar/pr4m0d-MISTer-bin#26]
There is no sound anymore when I set free play on coin 1. Used the new build v2182022

**Comment by zakk4223** [comment]
This is because when you set Coin 1 to free play the 'coin 2' dips change into something different. One of those disables sound. 
Set Coin 2 to 'Free Play' and that should set those dips so you have music+effects+non-rotated controls

**Comment by hardyhell** [comment]
But it’s not intended like that. Right?

**Comment by zakk4223** [comment]
It is. That’s how the dips function on actual hardware. I’d have to double check the actual positions/values but the coin 2 dips do change based on coin 1 being free play or not.

**Comment by hardyhell** [comment]
Ok. If you can confirm that it’s on the real hardware too. Sorry then for not knowing that garegga behaves like that.
