### ISSUE TITLE
Raizing cores not working / "no rbf found" message

### ISSUE THREAD

**Issue by Klatrymadon** [psomashekar/pr4m0d-MISTer-bin#28]
Hi everyone, 

Since the Batrider core was released, I've had the same issue with all of the Raizing games: selecting an .mra file from the '_Arcade' directory just kicks me back to the main menu of the OSD. If I try to start one of the games while another core is open, I get a little more info: "no rbf found!"

As far as I'm aware, everything is in the right place. The .rbf files are in '_Arcade/cores', the .mra files are in '_Arcade', and the relevant roms are in 'games/mame'. I've tried running the 'arcade organiser' and 'mame-getter' scripts to no avail. Have I gone wrong somewhere?

Thank you very much!

Best regards,
Mike

**Comment by psomashekar** [comment]
https://github.com/psomashekar/pr4m0d-MISTer-bin/issues/27
