### ISSUE TITLE
Sprite vertical stripping

### ISSUE THREAD

**Issue by Botvinnik92** [psomashekar/pr4m0d-MISTer-bin#3]
Hi,
This is probably an already known issue, but I have noticed that sometimes while playing sprites look vertically 'stripped'. This specially noticeable when an explosion occurs or a bomb is used, as can be seen in the picture.
Otherwise, the core looks superb. Congrats for such an amazing work.
![IMG_20220602_202240](https://user-images.githubusercontent.com/93479629/171702427-24f76d65-d112-44e7-852a-f00fc45a255e.jpg)

**Comment by psomashekar** [comment]
Yea, this is fixed.
