### ISSUE TITLE
Coin and Start buttons are reversed

### ISSUE THREAD

**Issue by RetroBrewz** [psomashekar/pr4m0d-MISTer-bin#32]
Whichever buttons you map to Coin and Start end up being reversed.

**Comment by psomashekar** [comment]
@atrac17 I think reversed them for compatibility purposes. The mapping is also in the MRA.

**Comment by atrac17** [comment]
> Whichever buttons you map to Coin and Start end up being reversed.

@RetroBrewz they are flipped so the keyboard functions appropriately. Sorry buddy!

![D1OQsafXQAAaB1i](https://user-images.githubusercontent.com/32810066/182222225-61dbbc1c-0dea-468a-a233-49156645c877.png)

**Comment by RetroBrewz** [comment]
Awesome, thanks so much for the quick fix!!
