### ISSUE TITLE
FX Very Quiet

### ISSUE THREAD

**Issue by retrorepair** [psomashekar/pr4m0d-MISTer-bin#34]
I've noticed there is an option for increasing the volume of FX in the menu but it doesn't seem to make any difference.

For example, the PCM sound in on the title screen with the bullet effects you can hardly make out. Only the FM sound seems loud enough. The "Raizing" PCM sample at the start is very quiet also.

**Comment by psomashekar** [comment]
This is the old build. The new builds correct this. I wont provide builds here anymore btw. Please use mister-devel.
