### ISSUE TITLE
Battle garegga land sprites not syncing to background

### ISSUE THREAD

**Issue by theenemy-thd** [psomashekar/pr4m0d-MISTer-bin#35]
Not sure if it's some setting I'm not using/aware of but when I played battle garegga the sprites on the land/background (static tanks etc) move independently of the background on the horizontal scroll.

Not sure if this is how garegga is but examining videos of the pcb I can't see this.

**Comment by psomashekar** [comment]
No this shouldn't happen normally, and I have not seen this reported. Hopefully when we fix up the clocks and other aspects of SDRAM, it will be smoother. But, basically all layers have scroll values that are controlled by the game program, so the calculation of where objects appear in relation to scroll values should be correct if all else is correct.

**Comment by theenemy-thd** [comment]
Hopefully the clock fix will sort it, I'm very surprised no one else hasn't seen the land sprites moving slightly before or after the background when the horizontal scroll is moving ... it is very noticeable.

**Comment by psomashekar** [comment]
Fixed in main repo.
