### ISSUE TITLE
Subway appears suddenly in Stage 1

### ISSUE THREAD

**Issue by MaxSchultz** [psomashekar/pr4m0d-MISTer-bin#4]
I've had so much fun with this core already.  What a lovely piece of work @psomashekar!

I noticed that the subway train at the start of Stage 1 pops into view abruptly instead of sliding in smoothly.

<img width="564" alt="image" src="https://user-images.githubusercontent.com/664787/171967200-83dc4670-11e2-45ab-a72c-62ef8a178267.png">

PCB Video: https://youtu.be/eio0kDBqGTY?t=46

**Comment by psomashekar** [comment]
That is a good catch. I will have to investigate this, but after I have bakraid working completely.
