### ISSUE TITLE
Line in the middle of hdmi output

### ISSUE THREAD

**Issue by asturur** [psomashekar/pr4m0d-MISTer-bin#6]
Hi, first of all thanks for the work on this core.
I know is an alpha/beta, i don't expect it to work flawlessly or pretend a fix for this issue.

Said so, let me explain the issue i found testingt the core.
The game work great on native analog out.

On the other side my vertical monitor is a crt, connected to HDMI with sync setting set to 2, and then with a vga converter to a sony monitor at 640x480@60.

In this configuration, in the middle of the screen there is a vertical line where the frame slide, like if there was vsync tearing constantly in the middle of the screen.

I will try to film it with the phone if that is a unknown issue yet.

**Comment by asturur** [comment]
i see a similarity with 
https://github.com/psomashekar/pr4m0d-MISTer-bin/issues/3
I ll try to verify i m on the beta core rather than alpha ( even if i m pretty much sure i am )

**Comment by psomashekar** [comment]
The striping was already fixed I think for the most part. Please let me know if you have another case of it.
