### ISSUE TITLE
Display cropped of a few pixel lines up top (tested in 1080p)

### ISSUE THREAD

**Issue by eturquin** [psomashekar/pr4m0d-MISTer-bin#7]
Probably a known (and minor) bug already, but in case: it looks like the top of the screen is slightly cropped (by a few, say 2-5, pixels), ends up cropping the score (the top-most pixel row). Didn't find an option to shift it back down.

**Comment by psomashekar** [comment]
Confused this with another issue... Reopening

**Comment by eturquin** [comment]
Thanks @psomashekar for looking into this! Actually, what you described as fixed may well be what I had seen (score and bomb fragments seemingly displayed too high). Looking forward to trying a new build! :)

**Comment by eturquin** [comment]
Sweet! Thanks for your great work!
