### ISSUE TITLE
Dip switches for Japan B Version

### ISSUE THREAD

**Issue by jepapac** [psomashekar/pr4m0d-MISTer-bin#8]
For Japan B Version, the dip switch settings in the menu don't match the labels in the test mode. I don't seem to be able to find settings to enable the extra characters, special course, or character selection modes. It appears that dip switch bank 3 is not fully connected.

**Comment by atrac17** [comment]
Correct, the additional I/O mapping isn't wired.

**Comment by atrac17** [comment]
`
static INPUT_PORTS_START( batriderj )
	PORT_INCLUDE( batrider )

	PORT_MODIFY("SYS-DSW")  // Coin/System and DSWC
	// These dips are shown only when Coin_A is set to Free_Play, but they work in normal play mode too
	PORT_DIPNAME( 0x2000,   0x0000, "Guest Players" )           PORT_DIPLOCATION("SW3:!6")
	PORT_DIPSETTING(        0x0000, DEF_STR( Off ) )
	PORT_DIPSETTING(        0x2000, DEF_STR( On ) )
	PORT_DIPNAME( 0x4000,   0x0000, "Player Select" )           PORT_DIPLOCATION("SW3:!7")
	PORT_DIPSETTING(        0x0000, DEF_STR( Off ) )
	PORT_DIPSETTING(        0x4000, DEF_STR( On ) )
	PORT_DIPNAME( 0x8000,   0x0000, "Special Course" )          PORT_DIPLOCATION("SW3:!8")
	PORT_DIPSETTING(        0x0000, DEF_STR( Off ) )
	PORT_DIPSETTING(        0x8000, DEF_STR( On ) )
INPUT_PORTS_END`

It's just `batriderj` "Armed Police Batrider (Japan, B version) (Fri Feb 13 1998)".

**Comment by psomashekar** [comment]
I wonder if it's possible the bits are out of order in the MRA? Because all 24 bits are passed to the CPU, so it should be able to read all of them. I can test later and let you know.

**Comment by atrac17** [comment]
Please do, I think @owlnonymous moved them to 21 to 23. They didn't work for me. The dip labels are direct dumps from the xml's provided for the game. I just dumped them based on jtframe parameters. Sorry for causing trouble, just wanted to play the Japan B version.

Again, thanks for all your work!

**Comment by psomashekar** [comment]
To create the USA version, I followed the manual. Wondering if we have the manual for the B version available?

**Comment by jepapac** [comment]
the English and Japanese manuals are available here: http://www.world-of-arcades.net/R8zing/Batrider/Manual.htm

The dip switches are not all documented in the manuals. It may have been meant as a secret. The guest characters can be enabled with dip C-6, Player select with dip C-7, and Special Course Boss Attack C-8. ref: https://shmups.system11.org/viewtopic.php?t=71

thank you both for your work on this

**Comment by atrac17** [comment]
```
 * Armed Police Batrider                                                    *
 *       The button you use to select your ship not only determines its     *
 *       color, but affects its characteristics.                            *
 *           A: High main shot power, low option shot power.                *
 *              Average speed. Default autofire rate is 15 Hz.              *
 *           B: Low main shot power, high option shot power. Slightly       *
 *              slower than A type. Default autofire rate is 12 Hz.         *
 *           C: High main shot and option shot power, but lowest speed.     *
 *              Default autofire rate is 20 Hz.                             *
 *       START: Low main shot and option shot power, but highest speed.     *
 *              Default autofire rate is 10 Hz.                             *
 *                                                                          *
 * Note: The following features can also be enabled via dipswitches.        *
 *                                                                          *
 * PLAYER SELECT: After inserting a coin, input                             *
 *       UP  UP  DOWN  DOWN  LEFT  RIGHT  LEFT  RIGHT  B  A                 *
 *       You can select a single character instead of a team.               *
 * GUEST PLAYERS: After inserting a coin, input                             *
 *       UP  UP  DOWN  DOWN  LEFT  RIGHT  LEFT  RIGHT  A  B                 *
 *       You can use Mahou Daisakusen and Battle Garegga characters.        *
 * SPECIAL COURSE: After inserting a coin, input                            *
 *       UP  DOWN  UP  DOWN  LEFT  RIGHT  LEFT  RIGHT  A  B                 *
 *       You can select the Special course, which consists of bosses only.  *
 * STAGE EDIT: When you select your course, press A and B simultaneously.   *
 *       You can choose what order to play Stage 2, 3 and 4 in,             *
 *       or even skip them.                                                 *
 ****************************************************************************
```

@jepapac you can input these codes after inserting a coin to access the features. I haven't tried setting freeplay and then toggling the dips with the bit's @owlnonymous set.

The port mapping for `batrider` starts at [3175](https://github.com/mamedev/mame/blob/44c2dcc333ffe2843717f5ec2c99593ce4c9f2d0/src/mame/drivers/toaplan2.cpp#L3066) and then `batriderj` changes start after. DIP C has different I/O stuff. You should be able to do an if statement. I had to do something similar for a different romsets for a few of Jose's cores.

**Comment by owlnonymous** [comment]
I posted my modified MRA text here. https://pastebin.com/ErdTKCTT

**Comment by psomashekar** [comment]
working dips for japan B, just tested myself:

<switches default="00,00,00" base="8">
        <dip bits="0" name="Test Mode" ids="Off, On"/>
        <dip bits="1" name="Starting Coin" ids="1 Credit, 2 Credits"/>
        <dip bits="2,4" name="Coin 1" ids="1 Coin/1 Credit, 1 Coin/2 Credits, 1 Coin/3 Credits, 1 Coin/4 Credits, 2 Coins/1 Credit, 3 Coins/1 Credit, 4 Coins/1 Credit, Free Play"/>
        <dip bits="5,7" name="Coin 2" ids="1 Coin/1 Credit, 1 Coin/2 Credits, 1 Coin/3 Credits, 1 Coin/4 Credits, 2 Coins/1 Credit, 3 Coins/1 Credit, 4 Coins/1 Credit, Free Play"/>
        <dip bits="8,9" name="Start Rank" ids="Normal, Easy, Hard, Very Hard"/>
        <dip bits="10,11" name="Timer Rank" ids="Normal, Low, High, Highest"/>
        <dip bits="12,13" name="Player Counts" ids="3, 4, 2, 1"/>
        <dip bits="14,15" name="Extra Player" ids="1.5mil Each, 1mil Each, 2mil Each, No Extra"/>
        <dip bits="16" name="Screen Flip" ids="Off, On"/>
        <dip bits="17" name="Demo Sound" ids="On, No Sound"/>
        <dip bits="18" name="Stage Edit" ids="Disable, Enable"/>
        <dip bits="19" name="Continue Play" ids="Enable, Disable"/>
        <dip bits="20" name="Invincible" ids="Off, On"/>
        <dip bits="21" name="NO USE 6" ids="Off, On"/>
        <dip bits="22" name="NO USE 7" ids="Off, On"/>
        <dip bits="23" name="NO USE 8" ids="Off, On"/>
    </switches>

**Comment by psomashekar** [comment]
so, how it works is you set 2-4 and 5-7 to free play, and then to unlock everything, you set 21, 22 and 23 to on.

**Comment by psomashekar** [comment]
@jepapac submitted a PR that resolves this, similar to dips I posted above, though proper names for 21-23. Thanks!!!
