### ISSUE TITLE
Error bad rom 0 

### ISSUE THREAD

**Issue by bonna79** [psomashekar/pr4m0d-MISTer-bin#9]
The game initially worked, but after 1/2 reboots of the Mister FPGA, the game returns an error, when checking: 68k Rom0 Dad Deleted all files but the problem persists. The game initially worked, but after 1/2 restart of the Mister FPGA, the game returns an error, when checking: 68k Rom0 Dad Deleted all files but the problem persists. Used the same rom on the mame and it works. If I enter the dip switch, I am able to do the audio tests and other tests, but the rom test fails. rom on the mame and it works. If I enter the dip switch, I am able to do the audio tests and other tests, but the rom test fails

![Uploading image.jpg…]()

**Comment by bonna79** [comment]
![706F5F6D-1AC2-4C2E-8B5B-4AF96E2174BC](https://user-images.githubusercontent.com/70318818/172920374-81b7d796-7fa1-40fd-b135-1eb3cb3502f4.jpeg)

**Comment by MaxSchultz** [comment]
@bonna79 I experienced this once and I have a strong suspicion that the issue was heat related.  Do you have a fan/heatsink etc?

**Comment by bonna79** [comment]
Si ho in case con ventola e dissipatore . L’unico core che mi da noia è questo gioco . Quando metto core e i files necessari ci gioco per 30 e più minuti il giorno dopo , quando riaccendo il mister , il gioco non va più . Ecco là mister configurata con la ventola incorporata .

**Comment by bonna79** [comment]
![image](https://user-images.githubusercontent.com/70318818/173108270-3cdadeaa-5fbc-471d-87c6-0a34600d94d0.jpg)

**Comment by bonna79** [comment]
I forgot that the Version of the coach and the Os are those in the photo:

![image](https://user-images.githubusercontent.com/70318818/173112095-f4b02f16-3cec-48ab-9995-00d6ab93161e.jpeg)

**Comment by psomashekar** [comment]
I have not heard others report the issue, but I would think it's something with either the SDRAM, or rom/ mra.

**Comment by MaxSchultz** [comment]
Agreed.  Run memtest from your scripts or: https://github.com/MiSTer-devel/MemTest_MiSTer

Also check to make sure your MiSTer is up to date.  Try a fresh SD card install etc.

**Comment by bonna79** [comment]
Ok I took the memory test and after 120 minutes I couldn’t find any errors. Anyway the strange thing is that if I disconnect from the power grid there mister, the game starts, if the Restarting from the menu gives me error rom 0 or 2. If someone tells me what other rom mame I can use. Maybe I’ll turn you around the Roma I use.

My coach has 128 mb of ram.
![image](https://user-images.githubusercontent.com/70318818/173186047-1e371720-71b2-479c-b7fe-e561e7af9a8c.jpeg)

**Comment by vivithecanine** [comment]
Experiencing the same thing on a dual SDRAM MiSTer with the batrider from MAME 0.244

**Comment by dishwasherlove** [comment]
I am also experiencing this issue. No problem with Bakraid, just Bad ROM 0 on the USA .mra. Seem to be able to launch the Japanese B .mra fine after a cold reboot.

**Comment by psomashekar** [comment]
I tried with dual ram setup as well, but not able to replicate. I heard it may be due to merged/ non merged set issues.
